export default (req, res) => {
  res.statusCode = 200;
  res.json({
    meta: { product: 'brx', version: '1.0', branch: 'master' },
    links: {
      self: {
        href: 'https://screwfix.bloomreach.io/delivery/site/v1/channels/brxsaas/pages/brand/dewalt?brand=dewalt',
        type: 'external',
      },
      site: { href: '/brand/dewalt?brand=dewalt', type: 'internal' },
    },
    channel: {
      info: {
        props: {
          graphql_baseurl: 'https://graphql.screwfix.bloomreach.io',
          smDomainKey: '',
          smAccountId: '6128',
          smEndpoint: 'https://core.dxpapi.com/api/v1/core/',
          spaUrl: 'https://brxm-react-spa.herokuapp.com/',
        },
      },
    },
    root: { $ref: '/page/u82b530a8263e43f285b9dc51cf438354' },
    document: { $ref: '/page/uf0a2e868b29644f39b35532e18f9e145' },
    page: {
      u82b530a8263e43f285b9dc51cf438354: {
        id: 'p1',
        links: {
          self: {
            href: 'https://screwfix.bloomreach.io/delivery/site/v1/channels/brxsaas/pages/brand/dewalt?_hn:type=component-rendering&_hn:ref=p1&brand=dewalt',
            type: 'external',
          },
        },
        meta: { params: {} },
        name: 'one-column',
        label: 'One-Column Layout',
        type: 'component',
        componentClass: 'org.hippoecm.hst.core.component.GenericHstComponent',
        children: [
          { $ref: '/page/u4eedf2aa774148a4a925c6c85720c2e6' },
          { $ref: '/page/ua1024ab42bac419f8016d3f12b71be9c' },
          { $ref: '/page/u0f193a7118e44940ad30cd1b3997db45' },
          { $ref: '/page/u6904913b43b84a9d9fcf6c2b87b5592d' },
          { $ref: '/page/u4181707572d54fbfa2218538eb9589a6' },
          { $ref: '/page/u8e8dd67bbac24834b6881ce8f393e57a' },
        ],
      },
      uf0a2e868b29644f39b35532e18f9e145: {
        type: 'document',
        links: { site: { href: '/brand/dewalt', type: 'internal' } },
        meta: {},
        data: {
          name: 'dewalt',
          displayName: 'dewalt',
          date: null,
          image: 'https://www.screwfix.fr/media/images/brands/dewalt.png',
          title: 'Dewalt',
          introduction: '',
          content: { contentType: 'hippostd:html', value: '' },
          localeString: 'en',
          contentType: 'brxsaas:content',
          id: 'f0a2e868-b296-44f3-9b35-532e18f9e145',
        },
      },
      u4eedf2aa774148a4a925c6c85720c2e6: {
        id: 'p1_p1',
        links: {
          self: {
            href: 'https://screwfix.bloomreach.io/delivery/site/v1/channels/brxsaas/pages/brand/dewalt?_hn:type=component-rendering&_hn:ref=p1_p1&brand=dewalt',
            type: 'external',
          },
        },
        meta: { params: {} },
        name: 'top',
        type: 'component',
        componentClass: 'org.hippoecm.hst.core.component.GenericHstComponent',
        children: [{ $ref: '/page/ua24a2d6b7370402d8bbe32f31690283b' }],
      },
      ua1024ab42bac419f8016d3f12b71be9c: {
        id: 'p1_p2',
        links: {
          self: {
            href: 'https://screwfix.bloomreach.io/delivery/site/v1/channels/brxsaas/pages/brand/dewalt?_hn:type=component-rendering&_hn:ref=p1_p2&brand=dewalt',
            type: 'external',
          },
        },
        meta: { params: {} },
        name: 'main',
        type: 'component',
        componentClass: 'org.hippoecm.hst.core.component.GenericHstComponent',
        children: [{ $ref: '/page/u179b6abc9a6c48bc8ee07dbe9bff4f88' }],
      },
      u0f193a7118e44940ad30cd1b3997db45: {
        id: 'p1_p3',
        links: {
          self: {
            href: 'https://screwfix.bloomreach.io/delivery/site/v1/channels/brxsaas/pages/brand/dewalt?_hn:type=component-rendering&_hn:ref=p1_p3&brand=dewalt',
            type: 'external',
          },
        },
        meta: { params: {} },
        name: 'bottom',
        type: 'component',
        componentClass: 'org.hippoecm.hst.core.component.GenericHstComponent',
        children: [{ $ref: '/page/u6e643756fdbd4165b539bc0c435a2e9f' }],
      },
      u6904913b43b84a9d9fcf6c2b87b5592d: {
        id: 'p1_p4',
        links: {
          self: {
            href: 'https://screwfix.bloomreach.io/delivery/site/v1/channels/brxsaas/pages/brand/dewalt?_hn:type=component-rendering&_hn:ref=p1_p4&brand=dewalt',
            type: 'external',
          },
        },
        meta: {
          paramsInfo: { menu: 'main' },
          params: { selectedMenu: 'on', level: '2' },
        },
        name: 'menu',
        type: 'component',
        componentClass:
          'org.hippoecm.hst.component.support.bean.dynamic.MenuDynamicComponent',
        models: { menu: { $ref: '/page/u65a3ab4bf3de41e4bfb1e6899f96326f' } },
      },
      u4181707572d54fbfa2218538eb9589a6: {
        id: 'p1_p5',
        links: {
          self: {
            href: 'https://screwfix.bloomreach.io/delivery/site/v1/channels/brxsaas/pages/brand/dewalt?_hn:type=component-rendering&_hn:ref=p1_p5&brand=dewalt',
            type: 'external',
          },
        },
        meta: { params: {} },
        name: 'header',
        type: 'component',
        componentClass: 'org.hippoecm.hst.core.component.GenericHstComponent',
        children: [{ $ref: '/page/u2bf11e93c04a4de1953230f17c393fc9' }],
      },
      u8e8dd67bbac24834b6881ce8f393e57a: {
        id: 'p1_p6',
        links: {
          self: {
            href: 'https://screwfix.bloomreach.io/delivery/site/v1/channels/brxsaas/pages/brand/dewalt?_hn:type=component-rendering&_hn:ref=p1_p6&brand=dewalt',
            type: 'external',
          },
        },
        meta: { params: {} },
        name: 'footer',
        type: 'component',
        componentClass: 'org.hippoecm.hst.core.component.GenericHstComponent',
        children: [{ $ref: '/page/u5aa9bc5ba9274c94bfc2d1a859d7a312' }],
      },
      ua24a2d6b7370402d8bbe32f31690283b: {
        id: 'p1_p1_p1',
        links: {
          self: {
            href: 'https://screwfix.bloomreach.io/delivery/site/v1/channels/brxsaas/pages/brand/dewalt?_hn:type=component-rendering&_hn:ref=p1_p1_p1&brand=dewalt',
            type: 'external',
          },
        },
        meta: { params: {} },
        name: 'container',
        label: 'Top',
        type: 'container',
        xtype: 'hst.nomarkup',
        componentClass:
          'org.hippoecm.hst.builtin.components.StandardContainerComponent',
      },
      u179b6abc9a6c48bc8ee07dbe9bff4f88: {
        id: 'p1_p2_p1',
        links: {
          self: {
            href: 'https://screwfix.bloomreach.io/delivery/site/v1/channels/brxsaas/pages/brand/dewalt?_hn:type=component-rendering&_hn:ref=p1_p2_p1&brand=dewalt',
            type: 'external',
          },
        },
        meta: { params: {} },
        name: 'container',
        label: 'Main',
        type: 'container',
        xtype: 'hst.nomarkup',
        componentClass:
          'org.hippoecm.hst.builtin.components.StandardContainerComponent',
        children: [{ $ref: '/page/u1ee5257e44df4a459a7e65f93ee0d6a3' }],
      },
      u6e643756fdbd4165b539bc0c435a2e9f: {
        id: 'p1_p3_p1',
        links: {
          self: {
            href: 'https://screwfix.bloomreach.io/delivery/site/v1/channels/brxsaas/pages/brand/dewalt?_hn:type=component-rendering&_hn:ref=p1_p3_p1&brand=dewalt',
            type: 'external',
          },
        },
        meta: { params: {} },
        name: 'container',
        label: 'Bottom',
        type: 'container',
        xtype: 'hst.nomarkup',
        componentClass:
          'org.hippoecm.hst.builtin.components.StandardContainerComponent',
      },
      u65a3ab4bf3de41e4bfb1e6899f96326f: {
        type: 'menu',
        links: {},
        meta: {},
        data: {
          name: 'main',
          siteMenuItems: [
            {
              depth: 0,
              repositoryBased: false,
              properties: {
                'hst:referencesitemapitem': 'home',
                'hst:repobased': false,
              },
              name: 'TOOLS',
              expanded: false,
              selected: false,
              childMenuItems: [
                {
                  depth: 0,
                  repositoryBased: false,
                  properties: { 'hst:repobased': false },
                  name: 'POWER TOOLS',
                  expanded: false,
                  selected: false,
                  childMenuItems: [
                    {
                      depth: 0,
                      repositoryBased: false,
                      properties: {
                        'hst:externallink': '/brand/dewalt',
                        'hst:repobased': false,
                      },
                      name: 'Drills',
                      expanded: false,
                      selected: false,
                      childMenuItems: [],
                      parameters: {},
                      links: {
                        site: { href: '/brand/dewalt', type: 'external' },
                      },
                    },
                    {
                      depth: 0,
                      repositoryBased: false,
                      properties: { 'hst:repobased': false },
                      name: 'Saws',
                      expanded: false,
                      selected: false,
                      childMenuItems: [],
                      parameters: {},
                      links: {},
                    },
                    {
                      depth: 0,
                      repositoryBased: false,
                      properties: {
                        'hst:referencesitemapitem': 'products/bolts',
                        'hst:repobased': false,
                      },
                      name: 'Kits & Twinpacks',
                      expanded: false,
                      selected: false,
                      childMenuItems: [],
                      parameters: {},
                      links: {
                        site: { href: '/products/bolts', type: 'internal' },
                      },
                    },
                    {
                      depth: 0,
                      repositoryBased: false,
                      properties: { 'hst:repobased': false },
                      name: 'Workshop Machinery',
                      expanded: false,
                      selected: false,
                      childMenuItems: [],
                      parameters: {},
                      links: {},
                    },
                    {
                      depth: 0,
                      repositoryBased: false,
                      properties: { 'hst:repobased': false },
                      name: 'Sanders',
                      expanded: false,
                      selected: false,
                      childMenuItems: [],
                      parameters: {},
                      links: {},
                    },
                    {
                      depth: 0,
                      repositoryBased: false,
                      properties: { 'hst:repobased': false },
                      name: 'Polishers',
                      expanded: false,
                      selected: false,
                      childMenuItems: [],
                      parameters: {},
                      links: {},
                    },
                    {
                      depth: 0,
                      repositoryBased: false,
                      properties: { 'hst:repobased': false },
                      name: 'Angle Grinders',
                      expanded: false,
                      selected: false,
                      childMenuItems: [],
                      parameters: {},
                      links: {},
                    },
                    {
                      depth: 0,
                      repositoryBased: false,
                      properties: { 'hst:repobased': false },
                      name: 'Multi Tools',
                      expanded: false,
                      selected: false,
                      childMenuItems: [],
                      parameters: {},
                      links: {},
                    },
                    {
                      depth: 0,
                      repositoryBased: false,
                      properties: { 'hst:repobased': false },
                      name: 'Impact Drivers & Wrenches',
                      expanded: false,
                      selected: false,
                      childMenuItems: [],
                      parameters: {},
                      links: {},
                    },
                    {
                      depth: 0,
                      repositoryBased: false,
                      properties: { 'hst:repobased': false },
                      name: 'Nail Guns',
                      expanded: false,
                      selected: false,
                      childMenuItems: [],
                      parameters: {},
                      links: {},
                    },
                    {
                      depth: 0,
                      repositoryBased: false,
                      properties: { 'hst:repobased': false },
                      name: 'Routers',
                      expanded: false,
                      selected: false,
                      childMenuItems: [],
                      parameters: {},
                      links: {},
                    },
                    {
                      depth: 0,
                      repositoryBased: false,
                      properties: { 'hst:repobased': false },
                      name: 'Air Tools',
                      expanded: false,
                      selected: false,
                      childMenuItems: [],
                      parameters: {},
                      links: {},
                    },
                    {
                      depth: 0,
                      repositoryBased: false,
                      properties: { 'hst:repobased': false },
                      name: 'Air Compressors',
                      expanded: false,
                      selected: false,
                      childMenuItems: [],
                      parameters: {},
                      links: {},
                    },
                  ],
                  parameters: {},
                  links: {},
                },
                {
                  depth: 0,
                  repositoryBased: false,
                  properties: { 'hst:repobased': false },
                  name: 'POWER TOOL ACCESSORIES',
                  expanded: false,
                  selected: false,
                  childMenuItems: [],
                  parameters: {},
                  links: {},
                },
                {
                  depth: 0,
                  repositoryBased: false,
                  properties: { 'hst:repobased': false },
                  name: 'HAND TOOLS',
                  expanded: false,
                  selected: false,
                  childMenuItems: [],
                  parameters: {},
                  links: {},
                },
                {
                  depth: 0,
                  repositoryBased: false,
                  properties: { 'hst:repobased': false },
                  name: 'TOOL STORAGE',
                  expanded: false,
                  selected: false,
                  childMenuItems: [],
                  parameters: {},
                  links: {},
                },
                {
                  depth: 0,
                  repositoryBased: false,
                  properties: { 'hst:repobased': false },
                  name: 'LEVELS & MEASURING',
                  expanded: false,
                  selected: false,
                  childMenuItems: [],
                  parameters: {},
                  links: {},
                },
                {
                  depth: 0,
                  repositoryBased: false,
                  properties: { 'hst:repobased': false },
                  name: 'TESTING EQUIPMENT',
                  expanded: false,
                  selected: false,
                  childMenuItems: [],
                  parameters: {},
                  links: {},
                },
              ],
              parameters: {},
              links: { site: { href: '/', type: 'internal' } },
            },
            {
              depth: 0,
              repositoryBased: false,
              properties: {
                'hst:referencesitemapitem': 'articles',
                'hst:repobased': false,
              },
              name: 'HEATING AND PLUMBING',
              expanded: false,
              selected: false,
              childMenuItems: [
                {
                  depth: 0,
                  repositoryBased: false,
                  properties: { 'hst:repobased': false },
                  name: 'RADIATORS',
                  expanded: false,
                  selected: false,
                  childMenuItems: [],
                  parameters: {},
                  links: {},
                },
                {
                  depth: 0,
                  repositoryBased: false,
                  properties: { 'hst:repobased': false },
                  name: 'Central Heating',
                  expanded: false,
                  selected: false,
                  childMenuItems: [],
                  parameters: {},
                  links: {},
                },
                {
                  depth: 0,
                  repositoryBased: false,
                  properties: { 'hst:repobased': false },
                  name: 'Plumbing',
                  expanded: false,
                  selected: false,
                  childMenuItems: [],
                  parameters: {},
                  links: {},
                },
                {
                  depth: 0,
                  repositoryBased: false,
                  properties: { 'hst:repobased': false },
                  name: 'Guttering & Drainage',
                  expanded: false,
                  selected: false,
                  childMenuItems: [],
                  parameters: {},
                  links: {},
                },
                {
                  depth: 0,
                  repositoryBased: false,
                  properties: { 'hst:repobased': false },
                  name: 'Fires, Stoves & Electric Heating',
                  expanded: false,
                  selected: false,
                  childMenuItems: [],
                  parameters: {},
                  links: {},
                },
              ],
              parameters: {},
              links: { site: { href: '/articles', type: 'internal' } },
            },
            {
              depth: 0,
              repositoryBased: false,
              properties: { 'hst:repobased': false },
              name: 'ELECTRICAL & LIGHTING',
              expanded: false,
              selected: false,
              childMenuItems: [
                {
                  depth: 0,
                  repositoryBased: false,
                  properties: { 'hst:repobased': false },
                  name: 'WIRING ACCESSORIES',
                  expanded: false,
                  selected: false,
                  childMenuItems: [],
                  parameters: {},
                  links: {},
                },
                {
                  depth: 0,
                  repositoryBased: false,
                  properties: { 'hst:repobased': false },
                  name: 'CABLE & CABLE MANAGEMENT',
                  expanded: false,
                  selected: false,
                  childMenuItems: [],
                  parameters: {},
                  links: {},
                },
                {
                  depth: 0,
                  repositoryBased: false,
                  properties: { 'hst:repobased': false },
                  name: 'POWER DISTRIBUTION & CIRCUIT PROTECTION',
                  expanded: false,
                  selected: false,
                  childMenuItems: [],
                  parameters: {},
                  links: {},
                },
                {
                  depth: 0,
                  repositoryBased: false,
                  properties: { 'hst:repobased': false },
                  name: 'DOMESTIC ELECTRICALS',
                  expanded: false,
                  selected: false,
                  childMenuItems: [],
                  parameters: {},
                  links: {},
                },
                {
                  depth: 0,
                  repositoryBased: false,
                  properties: { 'hst:repobased': false },
                  name: 'SMART HOMES',
                  expanded: false,
                  selected: false,
                  childMenuItems: [],
                  parameters: {},
                  links: {},
                },
                {
                  depth: 0,
                  repositoryBased: false,
                  properties: { 'hst:repobased': false },
                  name: 'LIGHTING',
                  expanded: false,
                  selected: false,
                  childMenuItems: [],
                  parameters: {},
                  links: {},
                },
              ],
              parameters: {},
              links: {},
            },
            {
              depth: 0,
              repositoryBased: false,
              properties: { 'hst:repobased': false },
              name: 'BATHROOMS & KITCHENS',
              expanded: false,
              selected: false,
              childMenuItems: [],
              parameters: {},
              links: {},
            },
            {
              depth: 0,
              repositoryBased: false,
              properties: { 'hst:repobased': false },
              name: 'OUTDOOR & GARDENING',
              expanded: false,
              selected: false,
              childMenuItems: [],
              parameters: {},
              links: {},
            },
            {
              depth: 0,
              repositoryBased: false,
              properties: { 'hst:repobased': false },
              name: 'SCREWS, NAILS & FIXINGS',
              expanded: false,
              selected: false,
              childMenuItems: [],
              parameters: {},
              links: {},
            },
            {
              depth: 0,
              repositoryBased: false,
              properties: { 'hst:repobased': false },
              name: 'SECURITY & IRONMONGERY',
              expanded: false,
              selected: false,
              childMenuItems: [],
              parameters: {},
              links: {},
            },
            {
              depth: 0,
              repositoryBased: false,
              properties: { 'hst:repobased': false },
              name: 'BULDINGS & DOORS',
              expanded: false,
              selected: false,
              childMenuItems: [],
              parameters: {},
              links: {},
            },
            {
              depth: 0,
              repositoryBased: false,
              properties: { 'hst:repobased': false },
              name: 'SAFETY & WORKWEAR',
              expanded: false,
              selected: false,
              childMenuItems: [],
              parameters: {},
              links: {},
            },
            {
              depth: 0,
              repositoryBased: false,
              properties: { 'hst:repobased': false },
              name: 'SEALANTS & ADHESIVES',
              expanded: false,
              selected: false,
              childMenuItems: [],
              parameters: {},
              links: {},
            },
            {
              depth: 0,
              repositoryBased: false,
              properties: { 'hst:repobased': false },
              name: 'STORAGE & LADDERS',
              expanded: false,
              selected: false,
              childMenuItems: [],
              parameters: {},
              links: {},
            },
            {
              depth: 0,
              repositoryBased: false,
              properties: { 'hst:repobased': false },
              name: 'AUTO & CLEANING',
              expanded: false,
              selected: false,
              childMenuItems: [],
              parameters: {},
              links: {},
            },
            {
              depth: 0,
              repositoryBased: false,
              properties: { 'hst:repobased': false },
              name: 'DECORATING',
              expanded: false,
              selected: false,
              childMenuItems: [],
              parameters: {},
              links: {},
            },
            {
              depth: 0,
              repositoryBased: false,
              properties: {
                'hst:repobased': false,
                'dxphst:upstreamshallowhash': 'unset',
                'dxphst:upstreamtreehash': 'unset',
                'dxphst:shallowhash': '705330A64B0A62FC3C45E7CEB1F7073B',
                'dxphst:addednode': true,
                'dxphst:treehash': '705330A64B0A62FC3C45E7CEB1F7073B',
              },
              name: 'Untitled',
              expanded: false,
              selected: false,
              childMenuItems: [],
              parameters: {},
              links: {},
            },
          ],
        },
      },
      u2bf11e93c04a4de1953230f17c393fc9: {
        id: 'p1_p5_p1',
        links: {
          self: {
            href: 'https://screwfix.bloomreach.io/delivery/site/v1/channels/brxsaas/pages/brand/dewalt?_hn:type=component-rendering&_hn:ref=p1_p5_p1&brand=dewalt',
            type: 'external',
          },
        },
        meta: { params: {} },
        name: 'container',
        label: 'Header',
        type: 'container',
        xtype: 'hst.nomarkup',
        componentClass:
          'org.hippoecm.hst.builtin.components.StandardContainerComponent',
        children: [{ $ref: '/page/u4e3b7143121f4bb7969b5fc7f576a3e1' }],
      },
      u5aa9bc5ba9274c94bfc2d1a859d7a312: {
        id: 'p1_p6_p1',
        links: {
          self: {
            href: 'https://screwfix.bloomreach.io/delivery/site/v1/channels/brxsaas/pages/brand/dewalt?_hn:type=component-rendering&_hn:ref=p1_p6_p1&brand=dewalt',
            type: 'external',
          },
        },
        meta: { params: {} },
        name: 'container',
        label: 'Footer',
        type: 'container',
        xtype: 'hst.nomarkup',
        componentClass:
          'org.hippoecm.hst.builtin.components.StandardContainerComponent',
        children: [{ $ref: '/page/u63555f2009e9430a91c2f40de772fa9c' }],
      },
      u1ee5257e44df4a459a7e65f93ee0d6a3: {
        id: 'p1_p2_p1_p1',
        links: {
          self: {
            href: 'https://screwfix.bloomreach.io/delivery/site/v1/channels/brxsaas/pages/brand/dewalt?_hn:type=component-rendering&_hn:ref=p1_p2_p1_p1&brand=dewalt',
            type: 'external',
          },
        },
        meta: {
          paramsInfo: { document1: '/page/u9f5ae4441d014a5ba3192d3682a7c827' },
          params: {},
        },
        name: 'HTMLComponent',
        label: 'HTML Component',
        type: 'container-item',
        ctype: 'HTMLComponent',
        componentClass:
          'org.hippoecm.hst.component.support.bean.dynamic.BaseHstDynamicComponent',
        models: {
          document1: { $ref: '/page/u9f5ae4441d014a5ba3192d3682a7c827' },
        },
      },
      u4e3b7143121f4bb7969b5fc7f576a3e1: {
        id: 'p1_p5_p1_p1',
        links: {
          self: {
            href: 'https://screwfix.bloomreach.io/delivery/site/v1/channels/brxsaas/pages/brand/dewalt?_hn:type=component-rendering&_hn:ref=p1_p5_p1_p1&brand=dewalt',
            type: 'external',
          },
        },
        meta: {
          paramsInfo: {
            suggestionsLimit: 5,
            document: '/page/u1240a5a457524c008372fb297749d391',
            suggestionsEnabled: true,
          },
          params: {},
        },
        name: 'search',
        label: 'Search Bar',
        type: 'container-item',
        ctype: 'SearchBar',
        componentClass:
          'org.hippoecm.hst.component.support.bean.dynamic.BaseHstDynamicComponent',
        models: {
          document: { $ref: '/page/u1240a5a457524c008372fb297749d391' },
        },
      },
      u63555f2009e9430a91c2f40de772fa9c: {
        id: 'p1_p6_p1_p1',
        links: {
          self: {
            href: 'https://screwfix.bloomreach.io/delivery/site/v1/channels/brxsaas/pages/brand/dewalt?_hn:type=component-rendering&_hn:ref=p1_p6_p1_p1&brand=dewalt',
            type: 'external',
          },
        },
        meta: {
          paramsInfo: {
            document4: '',
            document3: '',
            document5: '',
            document2: '/page/ubaa9a4c588264f658df45557e2ca6f52',
            document1: '/page/ue382676c3bfa48faadd19e78158a6473',
          },
          params: {},
        },
        name: 'navigation',
        label: 'Page navigation',
        type: 'container-item',
        ctype: 'Navigation',
        componentClass:
          'org.hippoecm.hst.component.support.bean.dynamic.BaseHstDynamicComponent',
        models: {
          document4: null,
          document3: null,
          document5: null,
          document2: { $ref: '/page/ubaa9a4c588264f658df45557e2ca6f52' },
          document1: { $ref: '/page/ue382676c3bfa48faadd19e78158a6473' },
        },
      },
      u9f5ae4441d014a5ba3192d3682a7c827: {
        type: 'document',
        links: { site: { type: 'unknown' } },
        meta: {},
        data: {
          name: 'dewalt-html-test',
          displayName: 'Dewalt HTML Test',
          test: null,
          html: '<style>\r\n\r\n/*featureblock layout*/\r\n\r\n .featureblock .row.block_image {\r\n    padding: 10px;\r\n    background-color: #fdb827;\r\n    width: 100% !important;\r\n    margin: 0 !important;\r\n    }\r\n    \r\n     .featureblock img {\r\n    height: inherit !important;\r\n    left: inherit !important;\r\n    margin-left: inherit !important;\r\n    position: inherit !important;\r\n    width: 100%;\r\n    }\r\n    \r\n     .featureblock .row.block_text {\r\n    margin: 22px 0 0 0 !important;\r\n    width: 100% !important;\r\n    }\r\n    \r\n     .featureblock p.sub_title {\r\n    font-family: archivo_narrowbold;\r\n    font-size: 16px;\r\n    text-transform: uppercase;\r\n    line-height: 1;\r\n    text-align: center;\r\n    }\r\n    \r\n     .featureblock .block_text p {\r\n    margin-left: 10px;\r\n    margin-right: 10px;\r\n    }\r\n    \r\n     .featureblock p {\r\n    text-align: center;\r\n    }\r\n    \r\n     .featureblock a {\r\n    color: white;\r\n    }\r\n    \r\n     .feature_container_one .featureblock .row.block_text {\r\n    min-height: 120px;\r\n    }\r\n    \r\n     span.row-title.neg-pad-top {\r\n    margin-top: -20px;\r\n    }\r\n    \r\n    @media only screen and (max-width: 40em) {\r\n     .featureblock:before,\r\n     .featureblock:after {\r\n    content: " ";\r\n    display: table;\r\n    }\r\n     .featureblock .row.block_image {\r\n    padding: 6px;\r\n    background-color: #fdb827;\r\n    width: 100px !important;\r\n    margin: 0 10px 0 0 !important;\r\n    float: left;\r\n    }\r\n     .featureblock .block_image_wrap {\r\n    margin-bottom: 15px\r\n    }\r\n     .featureblock img {\r\n    height: inherit !important;\r\n    left: inherit !important;\r\n    margin-left: inherit !important;\r\n    position: inherit !important;\r\n    width: 100%;\r\n    }\r\n     .featureblock .row.block_text {\r\n    margin: 0 0 !important;\r\n    width: 100% !important;\r\n    }\r\n     .featureblock p.sub_title {\r\n    font-family: archivo_narrowbold;\r\n    font-size: 16px;\r\n    text-transform: uppercase;\r\n    line-height: 1;\r\n    text-align: left;\r\n    }\r\n     .featureblock p {\r\n    text-align: left;\r\n    overflow: hidden;\r\n    }\r\n     .featureblock {\r\n    margin: 22px 0 !important;\r\n    }\r\n    }\r\n    \r\n    @media only screen and (min-width: 40.063em) and (max-width:64em) {\r\n     .feature_container_one .featureblock .row.block_text {\r\n    min-height: 165px;\r\n    }\r\n    }\r\n    \r\n    \r\n    /*End Feature Block styling*/\r\n    \r\n     .video_embed {\r\n    display: none;\r\n    }\r\n    \r\n     .video_content {\r\n    display: none;\r\n    }\r\n    \r\n     a.BackHome {\r\n    display: none;\r\n    }\r\n    \r\n    \r\n     .h1-styling {\r\n    margin-bottom: 15px;\r\n    margin-top: 10px;\r\n    }\r\n    \r\n     .h1-styling h1 {\r\n    color: #FFF;\r\n    font-size: 26px;\r\n    font-family: archivo_narrowbold, sans-serif;\r\n    margin-bottom: 15px;\r\n    display: inline !important;\r\n    }\r\n    \r\n    \r\n     .row-wrp--mod--h2fix {\r\n    margin: 0 -.3em;\r\n    }\r\n    \r\n     .row-wrp--mod--blockfix {\r\n    margin: 0 -.3em;\r\n    }\r\n    \r\n    body {\r\n    background-color:#000!important;\r\n    }\r\n    \r\n     p {\r\n    color: #fff;\r\n    }\r\n    \r\n     .h2 {\r\n    color: #fff;\r\n    }\r\n    \r\n     .certona-tile__container, .mt__item {\r\n    border: 1px solid #fff;\r\n    }\r\n    \r\n     .h2.underline {\r\n    border-bottom: 1px solid #ffffff;\r\n    margin-top: 45px;\r\n    }\r\n    \r\n     .slider-certona .pagi__link {\r\n    top: -73px;\r\n    }\r\n    \r\n    \r\n     .mt__item-description p {\r\n    color: #000;\r\n    }\r\n    \r\n     .mt__item {\r\n    border: 1px solid #fdb827;\r\n    background-color: #fdb827;\r\n    }\r\n    \r\n     .mt__item .h3{\r\n    background:#fdb827;\r\n    }\r\n    \r\n     .mt__item .cat-link {\r\n    height: 100%;\r\n    padding: 9px 9px 0;\r\n    color: #000;\r\n    }\r\n    \r\n     .mt__item .cat-link .mt__item-description p a {\r\n    color: #000;\r\n    font-weight: bold;\r\n    }\r\n    \r\n     .mt__item .mt__item-title .h3 {\r\n    color: #000;\r\n    }\r\n    \r\n     .mt__item .mt__item-title .brand-title {\r\n    display: table-cell;\r\n    vertical-align: middle;\r\n    text-align: center;\r\n    text-transform: uppercase;\r\n    margin: 0;\r\n    padding: 0;\r\n    font-size: 16px;\r\n    line-height: 16px;\r\n    font-family: archivo_narrowbold,sans-serif;\r\n    }\r\n    \r\n     .row-title {\r\n    width: 100%;\r\n    border-bottom: 1px solid #fff;\r\n    float: left;\r\n    margin: 26px 0 24px;\r\n    position: relative;\r\n    }\r\n    \r\n     .row-title h2 {\r\n    font-family: archivo_narrowbold, sans-serif;\r\n    font-size: 26px;\r\n    line-height: 26px;\r\n    position: relative;\r\n    left: 0;\r\n    bottom: 0;\r\n    margin-bottom: 15px;\r\n    color: #fff;\r\n    }\r\n    \r\n    #titleshort {\r\n    Width: 50%;\r\n    }\r\n    \r\n     .row-title .homeLink {\r\n    font-family: archivo_narrowbold, sans-serif;\r\n    font-size: 18px;\r\n    line-height: 18px;\r\n    position: absolute;\r\n    right: 0;\r\n    bottom: 0;\r\n    margin-bottom: 15px;\r\n    color: #fff;\r\n    }\r\n    \r\n     .full_width_banner .banner_content .mn_head {\r\n    color:#ffffff;\r\n    }\r\n    \r\n    .row-wrp--mod.top-margin {\r\n    margin-top: 15px;\r\n    }\r\n    \r\n    \r\n    /*sml-only*/\r\n    @media only screen and (max-width: 40em) {\r\n    \r\n     .mn_head {\r\n    display: none;\r\n    }\r\n    \r\n    \r\n     .h1-styling h1 {\r\n    font-size: 22px;\r\n    }\r\n    \r\n     .mt__item {\r\n    min-height: 100px;\r\n    }\r\n    \r\n     .brand-block .lg-8 md-8 sm-24 cols .mt__item equal {\r\n    height: 100px!important;\r\n    }\r\n    \r\n     .banner-mg-wrap {\r\n    height: 179px;\r\n    }\r\n    \r\n     .full_width_banner .gtough {\r\n    display:none;\r\n    }\r\n    \r\n     .full_width_banner .pocfoc {\r\n    display:none;\r\n    }\r\n    \r\n     .banner-mg-wrap img {\r\n    height: 179px;\r\n    margin: auto;\r\n    position: relative;\r\n    left: 0%;\r\n    }\r\n    \r\n     .full_width_banner .full_width_wrp {\r\n    position:relative;\r\n    text-align:center;\r\n    background-image: url("//www.screwfix.com/images/general/assets/gfx/headerbgtest_sm.png");\r\n    background-repeat:repeat-x;\r\n    padding: 0 0.6em;\r\n    }\r\n    \r\n     .full_width_banner .banner_content {\r\n    width: 100%;\r\n    font-size:10px;\r\n    }\r\n    \r\n     .full_width_banner .banner_content .mn_head {\r\n    border:none;\r\n    }\r\n    \r\n     .full_width_banner .banner_content .mn_head .mn_copy {\r\n    display:none!important;\r\n    }\r\n    \r\n     .full_width_banner .banner_content .mn_head .mn_tag {\r\n    display:none!important;\r\n    }\r\n    \r\n     .row-title {\r\n    margin:10px 0 12px;\r\n    }\r\n    \r\n     .row-title h2 {\r\n    font-size: 22px;\r\n    line-height: 22px;\r\n    margin-bottom: 15px;\r\n    }\r\n    \r\n     .row-title .ViewAllLink {\r\n    font-size: 16px;\r\n    line-height: 16px;\r\n    margin-bottom: 15px;\r\n    }\r\n    \r\n     .cat-link .mt__item-description {\r\n    display:none!important;\r\n    }\r\n    \r\n     .mt__item .mt__item-title {\r\n    height: 50px;\r\n    }\r\n    \r\n     .row-wrp--mod {\r\n    margin-right: -.5em;\r\n    margin-left: -.5em;\r\n    }\r\n    \r\n    \r\n    }\r\n    \r\n    \r\n    /*med-only*/\r\n    @media only screen and (max-width: 64em) and (min-width: 40.063em) {\r\n    \r\n    \r\n    \r\n     .mn_head p {\r\n    display:none;\r\n    }\r\n    \r\n    img.DewaltLogo {\r\n    position: absolute;\r\n    z-index: 1;\r\n    margin-top: 42px;\r\n    }\r\n    \r\n    img.DewaltLogosub {\r\n    position: absolute;\r\n    z-index: 1;\r\n    margin-top: 60px;\r\n    }\r\n    \r\n    img.DeWaltFlexVoltLogo {\r\n    position: absolute;\r\n    z-index: 1;\r\n    margin-top: 60px;\r\n    }\r\n    \r\n     .banner-mg-wrap {\r\n    height: 307px;\r\n    }\r\n    \r\n     .banner-mg-wrap img {\r\n    height: 323px;\r\n    margin-right: 35%;\r\n    position: relative;\r\n    }\r\n    \r\n     .dewalt_main img {\r\n    height: 323px;\r\n    left: 56%;\r\n    margin-top: -30px;\r\n    }\r\n    \r\n     .dewalt_pta img {\r\n    height: 323px;\r\n    left: 58%;\r\n    }\r\n    \r\n     .dewalt_handtools img {\r\n    height: 323px;\r\n    left: 54%;\r\n    }\r\n    \r\n     .dewalt_tool_storage img {\r\n    height: 323px;\r\n    left: 52%;\r\n    }\r\n    \r\n     .dewalt_levels img {\r\n    height: 323px;\r\n    left: 57%;\r\n    }\r\n    \r\n     .dewalt_snf img {\r\n    height: 323px;\r\n    left: 62%;\r\n    }\r\n    \r\n     .dewalt_flexvolt img {\r\n    height: 323px;\r\n    left: 53%;\r\n    }\r\n    \r\n     .full_width_banner .full_width_wrp {\r\n    position:relative;\r\n    text-align:center;\r\n    background-image: url("//www.screwfix.com/images/general/assets/gfx/headerbgtest_md.png");\r\n    background-repeat:repeat-x;\r\n    padding: 0 0.6em;\r\n    }\r\n    \r\n     .full_width_banner .banner_content .mn_head .mn_tag {\r\n    color: #fdb827;\r\n    display: block!important;\r\n    font-size: 27px;\r\n    padding: 1vw 0vw 0vw 1vw;\r\n    font-family: screwfix_betaregular;\r\n    }\r\n    \r\n     .full_width_banner .banner_content {\r\n    display:inline-block;\r\n    float:left;\r\n    }\r\n    \r\n    \r\n     .full_width_banner .banner_content .mn_head .mn_copy {\r\n    display:none!important;\r\n    }\r\n    \r\n     .full_width_banner .banner_content {\r\n    position:absolute;\r\n    z-index:1;\r\n    margin-top:15px;\r\n    }\r\n    \r\n     .full_width_banner .gtough {\r\n    position: absolute;\r\n    z-index: 1;\r\n    margin-top: 254px;\r\n    }\r\n    \r\n     .full_width_banner .pocfoc {\r\n    position: absolute;\r\n    z-index: 1;\r\n    margin-top: 280px;\r\n    }\r\n    \r\n     .mt__item .mt__item-title {\r\n    height: 50px;\r\n    }\r\n    \r\n    }\r\n    \r\n    /*lrg-only*/\r\n    @media screen and (min-width: 64.063em) {\r\n    \r\n    \r\n    \r\n    .DewaltLogo {\r\n    margin-top: 72px;\r\n    display: block;\r\n    position: absolute;\r\n    z-index: 1;\r\n    }\r\n    \r\n    .DewaltLogosub {\r\n    margin-top: 150px;\r\n    display: block;\r\n    position: absolute;\r\n    z-index: 1;\r\n    }\r\n    \r\n    .DeWaltFlexVoltLogo {\r\n    margin-top: 150px;\r\n    display: block;\r\n    position: absolute;\r\n    z-index: 1;\r\n    }\r\n    \r\n    \r\n     .banner-mg-wrap {\r\n    height: 430px;\r\n    \r\n    }\r\n    \r\n     .banner-mg-wrap img {\r\n    height: 441px;\r\n    left: 60%;\r\n    margin-top: -31px;\r\n    }\r\n    \r\n    \r\n     .dewalt_tool_storage img {\r\n    height: 441px;\r\n    left: 64%;\r\n    }\r\n    \r\n     .dewalt_pta img {\r\n    height: 441px;\r\n    left: 58%;\r\n    }\r\n    \r\n     .dewalt_levels img {\r\n    height: 441px;\r\n    left: 62%;\r\n    }\r\n    \r\n     .dewalt_workwear img {\r\n    height: 441px;\r\n    left: 55%;\r\n    }\r\n    \r\n     .dewalt_snf img {\r\n    height: 441px;\r\n    left: 62%;\r\n    }\r\n    \r\n     .dewalt_flexvolt img {\r\n    height: 441px;\r\n    left: 62%;\r\n    }\r\n    \r\n     .full_width_banner .full_width_wrp {\r\n    position:relative;\r\n    text-align:center;\r\n    background-image: url("//www.screwfix.com/images/general/assets/gfx/headerbgtest_lg.png");\r\n    background-repeat:repeat-x;\r\n    padding: 0 0.6em;\r\n    }\r\n    \r\n     .full_width_banner .banner_content .mn_head .mn_title {\r\n    width: 230px;\r\n    height: 64px;\r\n    background: url("//www.screwfix.com/images/general/assets/gfx/dewalt-logo.png");\r\n    margin-top: 20%;\r\n    }\r\n    \r\n     .full_width_banner .banner_content .mn_head .mn_copy{\r\n    display:block!important;\r\n    font-family: screwfix_betaregular;\r\n    }\r\n    \r\n     .full_width_banner .banner_content .mn_head .mn_tag{\r\n    color: #fdb827;\r\n    display:block!important;\r\n    font-size:30px;\r\n    padding: 0.5vw 0vw 1vw 0vw;\r\n    font-family: screwfix_betaregular;\r\n    }\r\n    \r\n     .full_width_banner .banner_content .mn_head .mn_copy{\r\n    display:block!important;\r\n    font-size:14px;\r\n    color:#fff;\r\n    width: 345px;\r\n    }\r\n    \r\n     .full_width_banner .banner_content {\r\n    position:absolute;\r\n    z-index:1;\r\n    margin-top:-15px;\r\n    }\r\n    \r\n     .full_width_banner .gtough {\r\n    position: absolute;\r\n    z-index: 1;\r\n    margin-top: 360px;\r\n    }\r\n    \r\n     .full_width_banner .pocfoc {\r\n    position: absolute;\r\n    z-index: 1;\r\n    margin-top: 384px;\r\n    }\r\n    \r\n    \r\n    }\r\n</style>\r\n<div><div class="full_width_banner main-header"></div><div class="full_width_banner main-header"></div><div class="full_width_banner main-header"><div class="row"><div class="lg-24 md-24 sm-24"><div class="mn_head">\r\n   <img src="//www.screwfix.com/images/general/assets/gfx/dewalt-logo.png" alt="DeWalt Logo" class="DewaltLogo">\r\n </div><div class="gtough" style="left: 459px;">\r\n\t\t\t<img data-src-small="//www.screwfix.com/images/general/assets/gfx/guaranteedtough_lg.png" data-src-medium="//www.screwfix.com/images/general/assets/gfx/guaranteedtough_md.png" data-src-large="//www.screwfix.com/images/general/assets/gfx/guaranteedtough_lg.png" class="swap" data-alt="Shop our great range of DeWalt" src="//www.screwfix.com/images/general/assets/gfx/guaranteedtough_lg.png" loading="eager">\r\n</div>\r\n\r\n<div class="full_width_wrp" style="width: 1428px; left: -144px;"><div class="dewalt_main banner-mg-wrap">\r\n\t\t\t<img data-src-small="//www.screwfix.com/images/general/assets/gfx/dewalt-mainheaderbannertest_sm.png" data-src-medium="//www.screwfix.com/images/general/assets/gfx/dewalt-mainheaderbanner_md.png" data-src-large="//www.screwfix.com/images/general/assets/gfx/dewalt-mainheaderbanner_lg.png" class="swap" data-alt="Shop our great range of DeWalt" src="//www.screwfix.com/images/general/assets/gfx/dewalt-mainheaderbanner_lg.png" loading="eager">\r\n</div>\r\n\r\n</div></div></div></div></div>',
          localeString: 'en',
          contentType: 'brxsaas:HTMLDocument',
          id: '9f5ae444-1d01-4a5b-a319-2d3682a7c827',
        },
      },
      u1240a5a457524c008372fb297749d391: {
        type: 'document',
        links: { site: { href: '/search', type: 'internal' } },
        meta: {},
        data: {
          name: 'search',
          displayName: 'Search',
          date: null,
          image: null,
          title: 'Search',
          introduction: null,
          content: { contentType: 'hippostd:html', value: '' },
          localeString: 'en',
          contentType: 'brxsaas:content',
          id: '1240a5a4-5752-4c00-8372-fb297749d391',
        },
      },
      ue382676c3bfa48faadd19e78158a6473: {
        type: 'document',
        links: { site: { href: '/terms-of-use', type: 'internal' } },
        meta: {},
        data: {
          name: 'terms-of-use',
          displayName: 'Terms of Use',
          date: null,
          image: null,
          title: 'Terms of Use',
          introduction: null,
          content: {
            contentType: 'hippostd:html',
            value:
              '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec a arcu porta, tincidunt lacus non, fermentum ante. Sed ac eros porttitor lorem condimentum sollicitudin eget quis mauris. Morbi in felis vel sapien finibus ullamcorper. Vivamus tempor, tellus vitae aliquam vulputate, quam arcu congue nisi, a accumsan elit ipsum porttitor ipsum. Suspendisse maximus, urna eget dapibus consequat, eros leo facilisis nulla, id condimentum massa justo in orci. Phasellus egestas iaculis justo, at vehicula arcu tincidunt vel. Vestibulum eget ornare eros.</p>\n<p>Pellentesque dictum ornare nibh, vitae porttitor risus posuere eget. Pellentesque eget suscipit neque. Morbi et tempor enim. Integer viverra urna non ornare porttitor. Nullam fringilla sapien massa, ac auctor lacus porttitor sit amet. Donec a dui luctus, aliquet felis nec, euismod arcu. Pellentesque et volutpat purus, eget aliquam dui. Phasellus eu enim vitae nisi lobortis euismod vel ac massa. Pellentesque id vestibulum metus, nec accumsan magna. Ut dolor diam, hendrerit mollis mattis at, dapibus id leo. Phasellus at imperdiet metus. Maecenas quis purus eleifend, luctus mauris et, vestibulum purus. Donec ac leo ut leo egestas blandit vel ac justo. Ut eget blandit arcu. Nunc interdum dui massa, a elementum nulla interdum quis.</p>',
          },
          localeString: 'en',
          contentType: 'brxsaas:content',
          id: 'e382676c-3bfa-48fa-add1-9e78158a6473',
        },
      },
      ubaa9a4c588264f658df45557e2ca6f52: {
        type: 'document',
        links: { site: { href: '/privacy-declaration', type: 'internal' } },
        meta: {},
        data: {
          name: 'privacy-declaration',
          displayName: 'Privacy Declaration',
          date: null,
          image: null,
          title: 'Privacy Declaration',
          introduction: null,
          content: {
            contentType: 'hippostd:html',
            value:
              '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec a arcu porta, tincidunt lacus non, fermentum ante. Sed ac eros porttitor lorem condimentum sollicitudin eget quis mauris. Morbi in felis vel sapien finibus ullamcorper. Vivamus tempor, tellus vitae aliquam vulputate, quam arcu congue nisi, a accumsan elit ipsum porttitor ipsum. Suspendisse maximus, urna eget dapibus consequat, eros leo facilisis nulla, id condimentum massa justo in orci. Phasellus egestas iaculis justo, at vehicula arcu tincidunt vel. Vestibulum eget ornare eros.</p>\n<p>Pellentesque dictum ornare nibh, vitae porttitor risus posuere eget. Pellentesque eget suscipit neque. Morbi et tempor enim. Integer viverra urna non ornare porttitor. Nullam fringilla sapien massa, ac auctor lacus porttitor sit amet. Donec a dui luctus, aliquet felis nec, euismod arcu. Pellentesque et volutpat purus, eget aliquam dui. Phasellus eu enim vitae nisi lobortis euismod vel ac massa. Pellentesque id vestibulum metus, nec accumsan magna. Ut dolor diam, hendrerit mollis mattis at, dapibus id leo. Phasellus at imperdiet metus. Maecenas quis purus eleifend, luctus mauris et, vestibulum purus. Donec ac leo ut leo egestas blandit vel ac justo. Ut eget blandit arcu. Nunc interdum dui massa, a elementum nulla interdum quis.</p>',
          },
          localeString: 'en',
          contentType: 'brxsaas:content',
          id: 'baa9a4c5-8826-4f65-8df4-5557e2ca6f52',
        },
      },
    },
    justproduct: {
      attr1: 'value1',
      attr2: {
        subattr1: 'sub val1',
        subattr2: 'sub val2',
      },
    },
  });
};
